version: '3.8'

services:
  postgres-portfolio-alone:
    image: postgres:15
    environment:
      POSTGRES_DB: portfolio_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1131
    ports:
      - "5433:5432"
    volumes:
      - postgres_portfolio_alone_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-alone:
    image: redis:7-alpine
    ports:
      - "6679:6379"
    volumes:
      - redis_alone_data:/data

  portfolio-service-alone:
    build:
      context: ../..        # 2 уровня вверх до investment-platform/
      dockerfile: ./portfolio-service/_docker/portfolio-service.local.Dockerfile
    ports:
      - "8082:8082"
      - "9089:9082"  # Actuator
    depends_on:
      postgres-portfolio-alone:
        condition: service_healthy
      redis-alone:
        condition: service_started
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-portfolio-alone:5432/portfolio_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1131
      - SPRING_REDIS_HOST=redis-alone
      - SPRING_REDIS_PORT=6379
      - FLYWAY_ENABLED=true

volumes:
  postgres_portfolio_alone_data:
  redis_alone_data: